<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Zend Backlog');
echo $this->doctype();

// ログイン情報を取得する
$authInfo = array();
$authStorage = Zend_Auth::getInstance()->getStorage();
$authInfo = (array)$authStorage->read();
?>

<html lang="ja">
<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/backlog.css'); ?>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
</head>
<body>
<header>
  <?php if($this->url(array('controller'=>'auth', 'action'=>'login-page')) !== $_SERVER["REQUEST_URI"]): ?>
    <?php if(empty($authInfo)): ?>
      <a href="<?php echo $this->url(array('controller'=>'auth',
          'action'=>'login-page'));?>">ログインページへ</a>
    <?php else: ?>
      <a href="<?php echo $this->url(array('controller'=>'auth',
          'action'=>'logout'));?>">ログアウト</a>
    <?php endif; ?>
  <?php endif; ?>
</header>
<div id="content">
    <h1><?php echo $this->escape($this->title); ?></h1>
    <?php echo $this->layout()->content; ?>
</div>
</body>
</html>
